version: '3.4'

services:

  onlineshopping:
    image: onlineshopping
    command: gunicorn yangpu2007360.wsgi:application --bind 0.0.0.0:8000
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 4444

    environment:
      - DB_NAME=yangpu2007360
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=bookstore3.c0pa5dbxh2kl.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-34-203-123-55.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
